### PR TITLE
Regulate the rerendering of child panels according to dimension of incoming selection

### PR DESCRIPTION
**Pull request by kevinrue**
See #580 

Particularly relevant to the heatmap panel, which may be configured to restrict on either or both incoming row and column selections

### CODE REVIEW

**Comment by LTLA** [comment]
You're in the right ballpark, but I wouldn't want to add more "reactive verbs" (i.e., counterparts of `.panelRepopulated`). These verbs describe how effects are propagated across 2+ steps of the dependency chain, i.e., from a panel to its grand-panel. New verbs should not be necessary to refine the behavior of a single panel.

Rather, what you want to do is to just avoid bumping the panel-specific rendering reactive at 

https://github.com/iSEE/iSEE/blob/ffebe817929662ba6975eb6b99ebfabe06e9c606/R/observers_child.R#L102

This is most easily achieved by inserting a few lines after L97, with a generic like `.multiSelectionResponsive`:

```
if (!.multiSelectionResponsive(instance)) {
     continue
}
```

which will just allow us to skip any rerendering attempt for CHMPs depending on its parameters. This generic would be a relative of `.multiSelectionRestricted` and `.multiSelectionInvalidated`.

**Comment by kevinrue** [comment]
I'm glad we're thinking along the same lines, but you're still missing one point.

None of the current verbs distinguish between row and column selections.

Initially, I tried to do exactly what you describe, using `.panelRepopulated` as the trigger verb.
However, when the CHMP received that trigger, it could not guess whether the new incoming selection was on the rows or the columns, which meant that the CHMP was rerendering in two cases were it shouldn't:

- the new incoming selection is on the rows, but the CHMP is using custom rows while actively using incoming column selections (i.e., `.multiSelectionResponsive`)
- the new incoming selection is on the columns, but the CHMP is not using incoming column selections while actively using incoming row selection (i.e., `.multiSelectionResponsive`, because it's NOT using custom rows)

Fee free to have a go and convince me otherwise, but I've tried a number of variants over the last couple of days, and this is the one that's doing everything with the minimum amount of code, AFAIK.

**Comment by LTLA** [comment]
Regardless, you should not do this with new verbs, and you should not be touching `modified` to achieve this effect (as this is also visible in `utils_reactive.R`). Put this information in a separate list that is not visible outside the observer.

You shouldn't need `.multiSelectionUpdateModes` because you get the information about the panel's transmitting dimension from `.multiSelectionDimension` anyway.

**Comment by kevinrue** [comment]
deprecated by #593

**Pull request closed without merging**
