### PR TITLE
Fixed duplicate names

### PR DESCRIPTION
**Pull request by LTLA**
Someone needs to go through and check all `select(ize)Input()`s that could take uncontrolled input (i.e., from the SE). I think we covered it by intercepting it at the `.cacheCommonInfo()` stage, but you never know.

Note that controlled inputs (e.g., the selection sources) are guaranteed to be unique and do not need protectino here.

### CODE REVIEW

**Comment by LTLA** [comment]
@kevinrue This'll need to be ported over to RELEASE as well.

**Comment by LTLA** [comment]
It seems that server-side updates are not affected by this, so we needn't worry about uniqueness in the row and column names heading into the `selectInput()`... though this does break the `data.frame` conversion for the `Table`s. Which in turn affects communication between panels, so I've just decided to coerce the dimnames to be unique at the start of the app.

One could reasonably argue that we should do the same thing for the column and row metadata as well, then we wouldn't have to throw down all of these `unique()` calls everywhere... This makes the fairly reasonable assumption that duplicated names anywhere are stupid and should be eliminated.

**Comment by kevinrue** [comment]
>  so I've just decided to coerce the dimnames to be unique at the start of the app.

That's the most reasonable behaviour to me.

> One could reasonably argue that we should do the same thing for the column and row metadata as well, then we wouldn't have to throw down all of these unique() calls everywhere... This makes the fairly reasonable assumption that duplicated names anywhere are stupid and should be eliminated.

I agree... which does not match the current state of the PR, meaning that some of the changes need to be reverted (i.e., removing all the `unique()` calls that you've just inserted), and instead calling `make.unique()` of all relevant dimnames.

If so, is it worth undoing some of the commits on this PR, or starting a new branch from `master` with only the newly agreed changes?

**Comment by kevinrue** [comment]
Fixed the PR, check if it behaves as you'd like @LTLA

**Comment by LTLA** [comment]
I think we'll just nuke this PR and start a new one.

**Comment by kevinrue** [comment]
Even after my updates?

**Comment by LTLA** [comment]
The cleaner needs to be a generic, as `reducedDimNames` might not work for arbitrary `se`s.

**Pull request closed without merging**
