### PR TITLE
Fixes #420

### LINKED ISSUE #420: [BUG] Panel sizes reset to default when re-opening Organize panels window
**Describe the bug**
Non-default panel sizes are reset to default values when the Organize panels window is closed and re-opened

**To Reproduce**
Steps to reproduce the behavior, e.g:
1. Open an empty iSEE application with `iSEEu::modeEmpty(sce)`
2. Click on Organize panels, add a panel and change the size from the default values
3. Click Apply settings
4. Click on Organize panels again
5. The panel size is reset to default values

**Expected behavior**
Modified panel sizes should be retained

**Desktop (please complete the following information):**
 - OS: Mac, Ubuntu (Bioc docker)
 - Browser: Chrome
 - Version: 2.0.0, 2.1.4

**Session info (please complete the following information)**

<details>
<summary><b>
Session info
</b></summary>

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] shiny_1.4.0.2               iSEEu_1.1.1                
 [3] iSEE_2.1.4                  SingleCellExperiment_1.11.2
 [5] SummarizedExperiment_1.19.4 DelayedArray_0.15.1        
 [7] matrixStats_0.56.0          Biobase_2.49.0             
 [9] GenomicRanges_1.41.1        GenomeInfoDb_1.25.0        
[11] IRanges_2.23.6              S4Vectors_0.27.9           
[13] BiocGenerics_0.35.2         BiocManager_1.30.10        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6           lattice_0.20-41        circlize_0.4.9        
 [4] shinyWidgets_0.5.3     png_0.1-7              digest_0.6.25         
 [7] mime_0.9               R6_2.4.1               ggplot2_3.3.1         
[10] colourpicker_1.0       pillar_1.4.4           GlobalOptions_0.1.1   
[13] zlibbioc_1.35.0        rlang_0.4.6            rstudioapi_0.11       
[16] miniUI_0.1.1.1         GetoptLong_0.1.8       Matrix_1.2-18         
[19] DT_0.13                shinyjs_1.1            splines_4.0.0         
[22] htmlwidgets_1.5.1      igraph_1.2.5           RCurl_1.98-1.2        
[25] munsell_0.5.0          vipor_0.4.5            compiler_4.0.0        
[28] httpuv_1.5.3.1         pkgconfig_2.0.3        shinyAce_0.4.1        
[31] shape_1.4.4            mgcv_1.8-31            htmltools_0.4.0       
[34] tidyselect_1.1.0       tibble_3.0.1           GenomeInfoDbData_1.2.3
[37] viridisLite_0.3.0      crayon_1.3.4           dplyr_1.0.0           
[40] later_1.0.0            bitops_1.0-6           grid_4.0.0            
[43] jsonlite_1.6.1         nlme_3.1-147           xtable_1.8-4          
[46] gtable_0.3.0           lifecycle_0.2.0        magrittr_1.5          
[49] scales_1.1.1           XVector_0.29.1         promises_1.1.0        
[52] ellipsis_0.3.1         vctrs_0.3.0            generics_0.0.2        
[55] rjson_0.2.20           RColorBrewer_1.1-2     tools_4.0.0           
[58] glue_1.4.1             purrr_0.3.4            crosstalk_1.1.0.1     
[61] yaml_2.2.1             fastmap_1.0.1          clue_0.3-57           
[64] colorspace_1.4-1       cluster_2.1.0          rintrojs_0.2.2        
[67] shinydashboard_0.7.1   ComplexHeatmap_2.5.3  
```
</details>

### PR DESCRIPTION
**Pull request by kevinrue**
Fixes #420

### CODE REVIEW

**Comment by LTLA** [comment]
Hold on, hold on. A much more effective solution would be to:

- replace the `uiOutput` in the modal with `.panel_organization`, and
- delete the `output$panelParams` section altogether.

This fixes the problem for width and height and potentially other future parameters that don't trip the `rerender` flag. It also eliminates the delay in response when you open the modal.

The current architecture is a hold-over from when we had the organization as a side bar.

**Comment by kevinrue** [comment]
OK.. I'll let you have a go at it. I'm all out of brainpower for today on this one.

**Comment by LTLA** [comment]
What problem does `bd3b521` try to fix?

**Comment by LTLA** [comment]
That was much harder than I thought. I forgot that we actually did need the `uiOutput("panelParam")` in order to respond to the panel order input. The problem arises because the modal opens with the old UI (and that old starting values) still in place, triggering the observers to reset the memory back to those old values. The solution is to simply turn off the observers until the rerendering is complete. 

In theory, there is a small gap where the UI is present and the observers are disabled where you could introduce some inconsistency between the observed settings and the memory, but this disappears in the blink of an eye when the rerendering starts, so I don't think that's a major concern.

**Pull request merged**
